// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package authdb

import (
	"database/sql"
	"time"
)

type Admin struct {
	ID int64 `json:"id"`
	// cryptom users are 1 and others are incremental
	AccountID   int64          `json:"account_id"`
	Email       string         `json:"email"`
	Password    string         `json:"password"`
	Phone       string         `json:"phone"`
	G2faEnabled sql.NullBool   `json:"g2fa_enabled"`
	G2faSecret  sql.NullString `json:"g2fa_secret"`
	Ban         sql.NullTime   `json:"ban"`
	LastLogin   time.Time      `json:"last_login"`
	// ip2location implementation
	LastLoginRaw string       `json:"last_login_raw"`
	CreatedAt    sql.NullTime `json:"created_at"`
	// syntax should be fixed ON UPDATE statement
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Kyc struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
	FirstName sql.NullString `json:"first_name"`
	LastName  string         `json:"last_name"`
	BirthDate string         `json:"birth_date"`
	// Turkish citizens are 1 and others are 2
	IDType       string       `json:"id_type"`
	IDCardNumber int64        `json:"id_card_number"`
	IDCardSerial int64        `json:"id_card_serial"`
	CreatedAt    sql.NullTime `json:"created_at"`
	// syntax should be fixed ON UPDATE statement
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type User struct {
	ID int64 `json:"id"`
	// normal users are 0, cryptom users are 1 and others are incremental
	AccountID      int64          `json:"account_id"`
	Email          string         `json:"email"`
	Phone          string         `json:"phone"`
	Password       string         `json:"password"`
	ReferralUserID sql.NullInt64  `json:"referral_user_id"`
	ReferralKey    sql.NullInt64  `json:"referral_key"`
	Country        string         `json:"country"`
	RegisterIp     string         `json:"register_ip"`
	RegisterDevice string         `json:"register_device"`
	Status         string         `json:"status"`
	G2faEnabled    bool           `json:"g2fa_enabled"`
	G2faSecret     sql.NullString `json:"g2fa_secret"`
	Ban            sql.NullTime   `json:"ban"`
	LastLogin      time.Time      `json:"last_login"`
	// ip2location implementation
	LastLoginRaw string       `json:"last_login_raw"`
	CreatedAt    sql.NullTime `json:"created_at"`
	// syntax should be fixed ON UPDATE statement
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}
